name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag shilongli0101/crawler:latest

    - name: Push the Docker image
      run: docker push shilongli0101/crawler:latest
      
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Tag the Docker image for GitHub Container Registry
      run: docker tag shilongli0101/crawler:latest ghcr.io/${{ github.repository_owner }}/crawler:latest
      
    - name: Push the Docker image to GitHub Container Registry
      run: docker push ghcr.io/${{ github.repository_owner }}/crawler:latest
